<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pandas" data-toc-modified-id="Pandas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pandas</a></span><ul class="toc-item"><li><span><a href="#Pandas-options" data-toc-modified-id="Pandas-options-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Pandas options</a></span></li><li><span><a href="#DataFrame" data-toc-modified-id="DataFrame-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>DataFrame</a></span></li></ul></li><li><span><a href="#Numpy" data-toc-modified-id="Numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Numpy</a></span></li><li><span><a href="#Data-Types" data-toc-modified-id="Data-Types-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Types</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Float-point-arithmatics" data-toc-modified-id="Float-point-arithmatics-3.0.0.1"><span class="toc-item-num">3.0.0.1&nbsp;&nbsp;</span>Float point arithmatics</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Optimization" data-toc-modified-id="Optimization-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Optimization</a></span></li></ul></div>

In [2]:
import os
import pandas                 as     pd
import time
import math
import sys
import numpy                  as     np
import random
from   pandas                 import Series, DataFrame
import seaborn                as     sns
import matplotlib.pyplot      as     plt
import time

# To increase the cell width
from IPython.core.display import display, HTML, Image
# display(HTML("<style>.container { width:100% !important; }</style>"))

C:\Users\musta\AppData\Local\Temp\ipykernel_8272\184817298.py:14: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML, Image


# Pandas

## Pandas options

In [ ]:
#Pandas options
pd.options.display.max_columns = None
# pd.options.display.max_rows    = None

# pd.set_option("display.max_rows", 500)

## DataFrame 

###### Create - Dataframe 

In [ ]:
#Usng lists
df = pd.DataFrame([1, 2, 3, 4])
df

In [ ]:
#Using lists + naming columns
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, 3, np.nan, 4]], columns=list('ABCD'))
df

In [ ]:
#Using Dictionary
df = pd.DataFrame({"first":[0, 1, 2, 3, 4], "second":[0, 10, 20, 30, 40]})
df

In [ ]:
#Using Dictionary + some values are missing in dictionary + Want NAN for missing values
d  = {"first":[0, 1, 2, 3, 4], "second":[0, 10, 20, 30]}
df = pd.DataFrame.from_dict(d, orient="index").T
df

In [ ]:
#Using Series
df = pd.DataFrame()
df["first"] = [1, 2, 3, 4]
df

In [ ]:
#Using Series + list
df = pd.DataFrame()
df["first"] = pd.Series([1, 2, 3, 4])
df

In [ ]:
#Using Series + numpy array
df = pd.DataFrame()
df["first"] = pd.Series(np.array([1, 2, 3, 4]))
df

###### Copy - DEEP and SOFT copy 

In [25]:
dict_1 = {"a":[1, 2, 3], "b":[11, 22, 33]}

In [ ]:
df_1 = pd.DataFrame(dict_1)
df_1

In [ ]:
df_4 = df_1[["a"]]
df_4

In [ ]:
df_4["a"].iloc[0] = 100
df_4

In [ ]:
df_1

In [ ]:
df_2 = df_1.copy(deep=True)
df_2

In [ ]:
df_3 = df_1.copy(deep=False)
df_3

In [ ]:
df_3["a"].iloc[0] = 100
df_3

In [ ]:
df_1

###### Change - Transpose dataframe 

In [ ]:
df_dict_2 = pd.DataFrame()
df_dict_2 = df_dict_2.append(data, ignore_index=True)
df_dict_2

In [ ]:
df_dict_2.transpose()

In [ ]:
df = 

###### Change -  order of columns 

In [ ]:
pd.DataFrame(data, columns=["year", "state", "pop"])

###### Change - specific rows data using pd.Series 

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [ ]:
frame2["debt"] = val

In [ ]:
frame2

###### Change - Index change 

In [ ]:
d = {"one" : [1., 2., 3., 4.],\
     "two" : [5., 6., 7., 8.]}

In [ ]:
a = pd.DataFrame(d, index=[4, 5, 6, 7])
a

In [ ]:
a = a.reset_index(drop=True)

In [ ]:
a

###### Change - data type of column

In [ ]:
a = {"a":[1, 2, 3], "b":[4, 5, 6]}
b = pd.DataFrame(a)
b

In [ ]:
b["b"] = b["b"].astype(str)
b["b"][1]

###### Change - Setting all values of one column to one value 

In [ ]:
frame2["debt"] = 16.5
frame2

In [ ]:
frame2["debt"]=np.arange(6)
frame2

###### Change - Relace Nan to 0 

In [ ]:
frame2["debt"] = frame2["debt"].fillna(0)
frame2

In [ ]:
#"ffill" method: replaces NAN values with precedding non-NAN values in the column 
frame2["debt"] = frame2["debt"].fillna(method="ffil")

###### Change -  Replace Values 

In [ ]:
frame2["state"].replace(["Ohio", "Nevada"],["California", "DC"], inplace=True)
frame2["pop"].replace(1.5, 5.1, inplace=True)
frame2

###### Change - rename column or index

In [ ]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df.rename(columns={"A": "a", "B": "c"}, inplace=True)
df

In [ ]:
df.rename(index={0: "x", 1: "y", 2: "z"}, inplace=True)
df

###### Change - Timeseries data frequency change: asfreq()

In [ ]:
index = pd.date_range('1/1/2000', periods=4, freq='T')
series = pd.Series([0.0, None, 2.0, 3.0], index=index)
df = pd.DataFrame({'s': series})
df

In [ ]:
#freq: 30 sec = 30S
#    -Min = 1 min
#    -2Min = 2min
#    -M = 1month
df.asfreq(freq='30S')
df.asfreq(freq='2Min')

In [ ]:
df.asfreq(freq='30S', fill_value=9.0)

In [ ]:
df.asfreq(freq='30S', method='bfill')

###### DTYPE - Change data type

In [2]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [1.0, 2.0, 3.0], 
                           'C': ['1.1.2010', '2.1.2011', '3.1.2011'], 
                           'D': ['1 days', '2 days', '3 days'],
                           'E': ['1', '2', '3']})

In [3]:
df.dtypes

A      int64
B    float64
C     object
D     object
E     object
dtype: object

In [10]:
df["B"] = df["B"].astype("float16")

In [11]:
df.dtypes

A      int64
B    float16
C     object
D     object
E     object
dtype: object

###### Combining Columns 1: using pd.Series 

In [ ]:
frame2["new_column_2"] = pd.Series(np.random.randn(len(frame2["year"])), index=frame2.index)
frame2

###### Combining Columns 2: Concat two df 

In [ ]:
df_1 = pd.DataFrame([[1,2,3], [4,5,6] ,[7,8,9]])
df_1

In [ ]:
df_2 = pd.DataFrame([[10,20,30], [40,50,60] ,[70,80,90]])
df_2

In [ ]:
df_3 = pd.concat([df_1, df_2])
df_3

In [ ]:
df_4 = pd.concat([df_1, df_2], axis=1)
df_4

In [ ]:
df_5 = pd.concat([df_1, df_2], axis=1, keys=["haha", "hoho"])
df_5

###### Combining Rows: Concat or Append

In [ ]:
#Copying specific rows of a dataframe to another dataframe
df_0 = pd.DataFrame([[0, 1, 2], [3, 4, 5], [6,7,8], [9,0,1]], columns=["one", "two", "three"])
df_0

In [ ]:
#Copying specific rows of a dataframe to another dataframe
df_1 = pd.DataFrame([[10, 11, 12], [13, 14, 15], [16,17,18], [19,20,21]], columns=["one", "two", "three"])
df_1

In [ ]:
df_2 = pd.concat([df_0, df_1])
# df_2.index = [0, 1, 2, 3, 4, 5, 6, 7]
df_2

In [ ]:
df_2 = pd.concat([df_0, df_1], ignore_index=True)
# df_2.index = [0, 1, 2, 3, 4, 5, 6, 7]
df_2

In [ ]:
#Using Append
df_2.append(df_0, ignore_index=True)

In [ ]:
#Using Append
df_3 = df_2.append(df_0.iloc[0], ignore_index=True)
df_3

In [ ]:
#Using Append
df_3 = df_2.append(df_0, ignore_index=True)
df_3

In [ ]:
df_3 = df_3.append(df_0.iloc[1])
df_3 = df_3.append(df_0.iloc[2])
df_3 = df_3.append(df_0.iloc[3])
df_3

###### Droping Columns 

In [ ]:
#This is it!
frame2.drop(columns=["new_column_1"])      #inplace=True, if you want to drop it permanently

In [ ]:
#This is it!
#Drop columns by integer columns numbers
frame2.drop(frame2.columns[0], axis=1, inplace=True)

In [ ]:
#IF Too many columns drop, create new
frame2 = frame2[["wantedColumn1", "wantedColumn2", "wantedColumn3"]]

In [ ]:
frame2.drop(["new_column_2"], axis=1)      #this only hides the columns
                                           #axis=1 -> removing columns, axis=0 -> removing rows (default)

In [ ]:
#This is it!
frame2.drop(["new_column_2"], axis=1, inplace=True)      #this acatually removes the column from the DataFrame

In [ ]:
frame2

###### Dropping Rows 

In [ ]:
frame2.drop(["one", "five"])

In [ ]:
frame2.drop(frame2.index[[1,3]])

In [ ]:
frame2.drop(frame2.index[1:3])      #inplace=True will remove these rows from the dataFrame

In [ ]:
frame2.columns[0]

In [ ]:
frame2.index[0:3]

In [ ]:
frame2.index[0]        #[0]  gives the actual value

In [ ]:
frame2.index[[0]]      #[[0]] gives Index

In [ ]:
frame2.index

In [ ]:
#This is it! 
#Drop columns by integer Row numbers
frame2.drop(frame2.index[2], inplace=True)

In [ ]:
#This is it!
#Drop events outside of target cup
df_GMSH.drop(df_GMSH[(pow(df_GMSH["x"] - (x_center), 2) + pow(df_GMSH["y"] - (y_center), 2)) > 0.75**2].index, inplace=True)

In [ ]:
frame2.drop(frame2.iloc[2], inplace=True)

###### Dropping Rows by condition 

In [ ]:
a = {"a": [1, 2, 3, 4, 5, 6], "b":[7, 8, 9, 10, 11, 12], "c":[13, 14, 15, 16, 17, 18]}

In [ ]:
df = pd.DataFrame(a)
df

In [ ]:
df.drop(    df[   ((df["b"] < 10) & (df["c"] == 15)) & (df["b"] >7)   ].index, inplace=True)
df

###### Get Size of df 

In [ ]:
#Get size of a pandas df via pandas memory_usage().sum():
df.memory_usage().sum()

In [ ]:
#Get size of a pandas df via pandas memory_usage().sum():
df.memory_usage().sum() / 1000000000

###### Iterate through columns 

In [ ]:
pop = {"Nevada":{2001:2.4, 2002:2.9}, "Ohio":{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

In [ ]:
for i in range(0, len(frame3.columns)):
    print(frame3.columns[i])

In [ ]:
for i in frame3:
    print(frame3[i])
    print("\n")    
    print(frame3[i].__class__)
    print("\n")

###### Iterate through rows 

In [ ]:
for i in range(0, len(frame3)):
    print(frame3.iloc[i])

###### Assign - value into specific cell 

In [ ]:
df = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df

In [ ]:
df['new_col'] = None
df

In [ ]:
#Assign Value into specific cell pf df
df.loc[1, 'new_col'] = 1
df

In [ ]:
#Assign Value into specific cell pf df
df.loc[df.col1 == 1, 'new_col'] = 1
df

###### Assign - list into column value 

In [ ]:
df = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df

In [ ]:
df['new_col'] = None
df

In [ ]:
#Assign Value into specific cell pf df
df.loc[df.col1 == 1, 'new_col'] = 1
df

In [ ]:
#NOT RECOMMENDED!!!!!!!
#    -If you do this you lose the VECTORIZATION functionality that comes with numpy
df.loc[df.col1 == 1, 'new_col'] = pd.Series([['a', 'b']] * len(df))
df

###### Selection - by PERCENTILE values 

In [ ]:
bin_partition_perc  = [0.15, 0.25]
bin_pos_eg_cos_list = df_buta_Eg_cos["mmsq_pi0"].quantile(bin_partition_perc).tolist()

bin_pos_eg_cos_list = [round(i, 3) for i in bin_pos_eg_cos_list]

In [ ]:
df = pd.DataFrame(np.array([[1, 1], [2, 10], [3, 100], [4, 100]]), columns=['a', 'b'])
df

In [ ]:
df.quantile(.1)

In [ ]:
df.quantile([.1, .5])

###### Selection - Random Selection - Sampling

In [ ]:
df = pd.DataFrame(np.random.uniform(low=10, high=20, size=(10, 5)), columns=["a", "b", "c", "d", "e"])
df

In [ ]:
df.sample()

In [ ]:
df.sample(3)

In [ ]:
df_2 = df.sample(frac=0.5)
df_2

###### Selection - basic - BEST

In [ ]:
pop = {"Nevada":{2001:2.4, 2002:2.9}, "Ohio":{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

In [ ]:
#Best way!!!!!!! use iloc!!
frame3.iloc[0:3]     

In [ ]:
frame3[0:3]     #show rows from 0 to 3

In [ ]:
frame3[1:3]["Ohio"]

In [ ]:
frame3.iloc[0][1]

In [ ]:
frame3.iloc[0:2, 1:2]      #Rows 0 to 1 and Columns 1 to 1

In [ ]:
frame3.iloc[0:2, 1:2].iloc[1]     #2nd element of (Rows 0 to 1 and Columns 1 to 1)

In [ ]:
frame3.loc[2000]["Ohio"]

In [ ]:
frame3.columns[0]

In [ ]:
frame3.index[0]

In [ ]:
frame3["Ohio"][2000]

In [ ]:
frame3["Ohio"][:]

In [ ]:
#SPEED

#SLOWEST
df_GPID_MVRT_SCPB.iloc[0]["epho"]

#SLOW
df_GPID_MVRT_SCPB.iloc[0].epho

#FASTEST (by factor of 5)
df_GPID_MVRT_SCPB["epho"].iloc[0]



###### Selection - rows and columns using iloc & loc 

In [ ]:
# dataFrame.loc[<ROWS RANGE> , <COLUMNS RANGE>]

# dataFrame.iloc[<ROWS INDEX RANGE> , <COLUMNS INDEX RANGE>]

In [ ]:
pop = {"Nevada":{2001:2.4, 2002:2.9}, "Ohio":{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

In [ ]:
#Using loc
frame3.loc[ : , ["Ohio"]]

In [ ]:
#Using loc
frame3.loc[ [2000, 2001] , ["Ohio"]]

In [ ]:
#Using iloc
frame3.iloc[:, :]

In [ ]:
frame3.iloc[ 0:1 , 1:2]

In [ ]:
frame3.iloc[ [0,1] , [0,1] ]

###### Selection - subset of columns not using loc 

In [ ]:
data_0 = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8), 'D' : np.random.randn(8)})
data_0

In [ ]:
data_0['B']

In [ ]:
#returns Series
data_0["A"]      #same as data_0.loc["a"] in this case of Series

In [ ]:
#returns dataframe if data_0 is dataframe
data_0[["A"]]      

In [ ]:
data_0[["B","C"]]  #retuns dataframe

###### Selection - based on column values

In [ ]:
#Read
df_read       = pd.read_csv("./dstmaker_Ppi0_3/df_GPID_dstmaker_Ppi0_3")
df_final_GPID = df_read.copy(deep=True)
#Need event number to be the index since there are events with multiple tracks
df_final_GPID.index = df_final_GPID["Unnamed: 0"]
df_final_GPID.drop(['Unnamed: 0'], axis=1, inplace=True)
# df_final_GPID.drop(['Unnamed: 1'], axis=1, inplace=True)
df_final_GPID.index.name = None

In [ ]:
df_final_GPID["mmsq_pi0"][df_final_GPID.pid==14]

In [ ]:
df_final_GPID["mmsq_pi0"][(df_final_GPID.pid==14) & (df_final_GPID.epho > 0.01)]

In [ ]:
df_final_GPID["mmsq_pi0"][(df_final_GPID.pid==14) | (df_final_GPID.epho > 0.01)]

###### Selection - Check if column value is within a list - isin()

In [ ]:
df = pd.DataFrame({'col1' : ['A', 'A', 'B', np.nan, 'D', 'C'], 'col2' : [2, 1, 9, 8, 7, 4], 'col3': [0, 1, 9, 4, 2, 3]})
df

In [ ]:
a = [1, 2, 4, 6, 8]

In [ ]:
df[df["col2"].isin(a)] 

###### Selection - Check is NaN

In [ ]:
#Df subset of df that is null
df_GMSH[df_GMSH["T_fin"].isnull()]

In [ ]:
#Df subset of df that is not null
df_GMSH[df_GMSH["T_fin"].isnull()==False]

In [ ]:
#Count # of null rows
df_GMSH["T_fin"].isnull().sum()

###### Show - Sort values 

In [ ]:
df = pd.DataFrame(np.random.rand(5, 4), columns=["a", "b", "c", "d"])
df

In [ ]:
df[["a","b"]].sort_values("a")

In [4]:
df = pd.DataFrame({'col1' : ['A', 'A', 'B', np.nan, 'D', 'C'], 'col2' : [2, 1, 9, 8, 7, 4], 'col3': [0, 1, 9, 4, 2, 3]})

In [ ]:
df.sort_values(by=['col2'], ascending=False)

###### Groupby

In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8), 'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
grouped_A  = df.groupby("A")
grouped_B  = df.groupby("B")
grouped_AB = df.groupby(["A", "B"])
grouped_AB_index = df.groupby(["A", "B"], as_index=False)    

In [ ]:
grouped_A.C.mean()

In [ ]:
#Same as "groupby"
df[df.A=="foo"].C.mean()

In [ ]:
#Same as "groupby"
df[df.A=="bar"].C.mean()

In [ ]:
grouped_AB.sum()

In [ ]:
grouped_AB.C.sum()

In [ ]:
grouped_AB["C"].sum()

In [ ]:
grouped_AB.mean()

In [ ]:
grouped_AB.C.mean()

In [ ]:
data_0 = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data_0

In [ ]:
grouped_AB_index.mean()

In [ ]:
data_0.__class__

In [ ]:
grouped_AB_index.C.mean()

In [ ]:
data_0["B":"C"]  #retuns series

In [ ]:
grouped_AB_index["C"].mean()

In [ ]:
data_0[["b","d"]]   

In [ ]:
data_0.loc[ : , 0:2]

###### create Series with multi-index 

In [ ]:
data_0 = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data_0

In [ ]:
data_0.index

In [ ]:
data_0.drop(("a","3"))

In [ ]:
data_0

###### Unstacking and Stacking: MultiIndex $\leftrightarrow$ regular dataframes 

In [ ]:
data_0.unstack()      #into a regular dataframe

In [ ]:
data_0.unstack().stack()      #back to multi-index

###### Hierarchial index on Columns and Rows 

In [ ]:
frame_0 = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                       columns=[['Ohio', 'Ohio', "Colorado"], ["Green", "Red", "Green"]])
frame_0

###### Put names on Hierarchical levels (indexes and columns)

In [ ]:
frame_0.index.names   = ["key1", "key2"]
frame_0.columns.names = ["state", "color"]  
frame_0

In [ ]:
frame_0.index

###### Drop Specific column in Multi-index dataframes 

In [ ]:
frame_0.drop(("a",1), inplace=True)      #drop one row of level a 
                                         #include inplace=True to permanently delete the row

In [ ]:
frame_0.drop(("a"), inplace=True)        #drop one level
                                         #include inplace=True to permanently delete the row

In [ ]:
frame_0

###### Accessing column and rows of a multi-indexed dataframe 

In [ ]:
frame_0[frame_0.columns[0]]   #access columns by using .columns[i]
                              #returns Series

In [ ]:
frame_0["Ohio"]               #access columns
                              #returns DataFrame

In [ ]:
frame_0["Ohio", "Green"]      #access column of column

In [ ]:
frame_0.loc["a"]              #access Rows of one level by loc + index lable

In [ ]:
len(frame_0.loc["a"])         #give number of rows in level a

In [ ]:
frame_0.loc[["a"]]            #access Rows of one level by loc + index lable + [[]] -> show lowest index level

In [ ]:
frame_0.loc["a", 2]           #access Row of Rows by loc + index lable

In [ ]:
frame_0.loc["a", 2]["Ohio"]           #access a column value of Row of Rows by loc + index lable

In [ ]:
frame_0.loc["a", 2]["Ohio"]["Green"]           #access a column of column of Row of Rows by loc + index lable

In [ ]:
frame_0.iloc[1]               #access one row by iloc -> iterates over row one by one, not by index labels
                              #[] gives Series

In [ ]:
frame_0.iloc[[1]]             #access one row by iloc -> iterates over row one by one, not by index labels
                              #[[]] gives Dataframe

In [ ]:
frame_0.iloc[1][1]            #access column of one row by ioc
                              #BEST WAY -> use iloc

In [ ]:
#Best Way!!
frame_0.iloc[1:2, 1:3]        #Rows 1 to 2-1, Columns 1 to 3-1

In [ ]:
frame_0.loc[["a",1]]

In [ ]:
frame_0.loc[["a"]]            #access Rows of one level by loc + index lable + [[]] -> show lowest index level

In [ ]:
frame_0.xs(("a"))             #Access rows of one level by .xs + index lable -> same as loc

In [ ]:
frame_0.xs(("a",2))           #Access a row of rows by .xs + index lable -> same as loc

In [ ]:
frame_0.xs(("a"))             #Access by .xs + index lable -> same as loc

###### Saving and Reading to files - CSV 

In [ ]:
df = pd.DataFrame({"a":[1, 2, 3], "b":[4, 5, 6], "c":[7, 8, 9]}, index=["haha", "hehe", "hoho"])
df

In [17]:
#Write to csv file
df.to_csv("./csv_practice")

In [18]:
#Read from csv file
df_new = pd.read_csv("./csv_practice")

In [ ]:
df_new

In [20]:
#When index are messes up after reading
df_new.index = df_new["Unnamed: 0"]
df_new.index.name = None
df_new.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
df_new

In [22]:
#Read from csv file - Preseve the index
df_new_2 = pd.read_csv("./csv_practice", index_col=0)

In [ ]:
df_new_2

###### Saving and Reading to files - Pickle

In [ ]:
df = pd.DataFrame({"a":[1, 2, 3], "b":[4, 5, 6], "c":[7, 8, 9]}, index=["haha", "hehe", "hoho"])
df

In [ ]:
#Save
df.to_pickle("./df_practice,pkl")

In [ ]:
#Read
df_new = pd.read_pickle("./df_practice,pkl")

In [ ]:
df_new

###### Apply function to a Column

In [ ]:
df = pd.DataFrame({"a":[1, 2, 3], "b":[4, 5, 6] })

In [ ]:
df

In [ ]:
df["a"] = df["a"].apply(lambda x: x+1)

In [ ]:
df

In [ ]:
df["a"] = df["a"].apply(lambda x: np.sqrt(abs(x)))

In [ ]:
df

In [ ]:
df["c"] = pd.Series( df["a"].apply(lambda x: np.sqrt(abs(x))))

In [ ]:
df["d"] = pd.Series(df["a"].apply(lambda x: np.sqrt(abs(x))), index=df.index)

In [ ]:
df

# Numpy

###### Summation 

In [9]:
#Sum of Array Elements along the axis

array1 = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])

#Plaing Summation
total = np.sum(array1)
print("Sum of elements = {:d}".format(total))

total_0_axis = np.sum(array1, axis=0)
print(f'Sum of elements at 0-axis is {total_0_axis}')

#dtype = output type
total_1_axis = np.sum(array1, axis=1, dtype=float)
print(f'Sum of elements at 1-axis is {total_1_axis}')

#Initial value of sum
total_2_axis = np.sum(array1, axis=1, dtype=float, initial=10)
print(f'Sum of elements at 1-axis is {total_2_axis}')

Sum of elements = 21
Sum of elements at 0-axis is [ 9 12]
Sum of elements at 1-axis is [ 3.  7. 11.]
Sum of elements at 1-axis is [13. 17. 21.]


###### Vector Addition

In [ ]:
a = [1, 2]
b = [3, 4]
c = a + b
print(c)

a = np.array(a)
b = np.array(b)
d = a + b
print(d)
print(d.tolist())

###### Random values 

In [ ]:
a = np.random.randint(2, 100, size=(2, 3, 4))
a

In [ ]:
b = np.random.uniform(low=5, high=10, size=(5,2,3))
b

In [ ]:
b = np.random.normal(loc=5, scale=10, size=(5,2,3))
b

In [ ]:
#Create random data
#    -20 random data points inbetween [0, 2]
x = np.random.rand(20)*2
x

###### Create array of numbers

In [ ]:
#Set spacing specifically.
x = np.arange(0, 2, 0.02)
x

In [ ]:
x = np.arange(12)
x

In [ ]:
x.shape = (3,4)
x

In [ ]:
x = np.array([1, 2, 3])
x

###### Add & Delete - Elements from arrays

In [48]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [49]:
a = np.append(a, [0])
a

array([1, 2, 3, 0])

In [52]:
a = np.append(a, [0], axis=0)
a

array([1, 2, 3, 0, 0])

In [20]:
#Delete 1th element in a
a = np.delete(a, 1)
a

array([1, 3, 0, 0])

###### Add & Delete - Row and Colume 

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#Add Row
newArray = np.append(a, [[50, 60, 70]], axis = 0)
newArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [50, 60, 70]])

In [42]:
#Add Column
newArray2 = np.append(a, [[1] ,[2] ,[3]], axis=1)
newArray2

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [43]:
#Delete Row
newArray3 = np.delete(newArray2, 1, axis=0)
newArray3

array([[1, 2, 3, 1],
       [7, 8, 9, 3]])

In [44]:
#Delete Column
newArray4 = np.delete(newArray2, 3, axis=1)
newArray4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Add & Delete -  newaxis - increase dimension 

In [ ]:
#1D becomes 2D
#2D becomes 3D
#...

Scenario 1: Np.newaxis comes in very handy when you want to explicitly convert an 1D array to either a row vector or a column vector.

In [ ]:
arr = np.arange(4)
print(arr.shape)
print(arr)
print("#====================")

# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]
print(row_vec.shape)
print(row_vec)
print("#====================")

# make it as column vector by inserting an axis along second dimension
col_vec = arr[:, np.newaxis]
print(col_vec.shape)
print(col_vec)
print("#====================")

# make it as column vector by inserting an axis along second dimension
col_vec = arr[..., np.newaxis]
print(col_vec.shape)
print(col_vec)


Scenario 2: When we want to make use of numpy broadcasting as part of some operation, for instance while doing addition of some arrays. The term numpy broadcasting describes how numpy treats arrays with different shapes during arithmetic operation. The smaller array, subject to some constraints, is “broadcast” across the larger arrays so that they have compatible shapes.

In [ ]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
print(x1.shape)
print(x2.shape)
print("#====================")

x1_new = x1[:, np.newaxis]
print(x1_new.shape)
print(x1_new)
print(x2)
print("#====================")



x1_new + x2

Scenario 3: You can use np.newaxis more than once to promote the array to higher dimensions.

In [ ]:
arr = np.arange(5*5).reshape(5,5)
print(arr.shape)

# promoting 2D array to a 5D array
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis]
print(arr_5D.shape)

print("#====================")
print(arr)
print(arr_5D)


###### Selction - based on CONDITIONS 

In [30]:
arr = np.arange(5, 30, 2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [31]:
#List of truth values when comparing a list to a singular value
arr<10

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [37]:
#store condition
a = (arr>6) & (arr<10)
print(a.__class__)
arr[a]

<class 'numpy.ndarray'>


array([7, 9])

In [16]:
#less than
newArr = arr[(arr>6) & (arr<10)]
newArr

array([7, 9])

In [6]:
#less than
newArr = arr[arr < 10]
newArr

array([5, 7, 9])

In [4]:
#Modulus
newArr = arr[arr%3==0]
newArr

array([ 9, 15, 21, 27])

In [5]:
#Multiple conditions
newArr = arr[(arr > 5) & (arr < 20)]
newArr

array([ 7,  9, 11, 13, 15, 17, 19])

In [6]:
arr2 = np.arange(55, 80, 2)
arr2

array([55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79])

In [10]:
#Desired conditions list
print(arr<10)

#Selects elements of arr2 which its positions are where the values of the 
#list of the desired conditions are true. 
print(arr2[arr<10])

[ True  True  True False False False False False False False False False
 False]
[55 57 59]


###### Selection - Set any negative values to 0 

In [7]:
a = np.array([1, -2, 3, -4, 5])

In [9]:
a[a<0] = 0
a

array([1, 0, 3, 0, 5])

###### Selection 

In [ ]:
x[1,3]

In [ ]:
x[1][3]      #2nd row, 4th column

In [ ]:
x[:, 2]      #all rows, 3rd column

In [ ]:
x[1:, 2]     #1st row to last row, 3rd column

###### Selection - iterative 

In [4]:
a = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

In [13]:
#From first elemet, iterate in steps of 2
a[0::2]

array(['a', 'c', 'e', 'g', 'i'], dtype='<U1')

In [14]:
#From first elemet, iterate in steps of 3
a[0::3]

array(['a', 'd', 'g', 'j'], dtype='<U1')

In [5]:
a[0:5]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [6]:
a[0:5:2]

array(['a', 'c', 'e'], dtype='<U1')

###### Selection - Multidimensional 

In [53]:
B = np.array([[0, 10, 20], [3, 4, 5], [6, 7, 8]]) 
B

array([[ 0, 10, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [54]:
B[:2,:]

array([[ 0, 10, 20],
       [ 3,  4,  5]])

In [55]:
B[:, ::2]

array([[ 0, 20],
       [ 3,  5],
       [ 6,  8]])

###### Selectoin - Ellipsis (...) 

* Ellipsis (...) = "as many as", "as needed"

In [77]:
B = np.array([[0, 10, 20], [3, 4, 5], [6, 7, 8]]) 
B

array([[ 0, 10, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
C = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
C

In [81]:
B[...]

array([[ 0, 10, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [82]:
B[0, ...]

array([ 0, 10, 20])

In [94]:
B[..., 0]

array([0, 3, 6])

In [63]:
B[0, ... , 2]

array(20)

In [83]:
B[1, Ellipsis , 1]

array(4)

In [84]:
C[0, ..., 0]    #Any elements that are in 0th element's 0th's element. 

array([0, 4, 8])

In [95]:
B[:, 0]

array([0, 3, 6])

In [88]:
C[0, ..., 1]    #Any elements that are in 0th element's 1th's element. 

array([1, 5, 9])

In [93]:
C[0, ..., 1, 3]    #Number is i-th element: any elements that are in 0th element's, 1st's element's, 3rd element

array(7)

###### convert dataframe to ndarray 

In [23]:
d = {"one" : [1., 2., 3., 4.],\
     "two" : [5., 6., 7., 8.]}

In [29]:
df0 = pd.DataFrame(d)
df0

one  two
0  1.0  5.0
1  2.0  6.0
2  3.0  7.0
3  4.0  8.0

In [33]:
df0_np = df0.values   #change to numpy.ndarray

In [34]:
df0_np

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])

In [ ]:
df0_np[0][0:2]      #show first row, 1st column to second column

In [ ]:
df0_np[0, :]        #show first row

In [ ]:
df0_np[:, 0]        #show first column

In [ ]:
df0_np.dtype

###### Remove NAN from list 

In [ ]:
a = [np.nan, np.nan, 1, 2, 3, np.nan, 4]
a

In [ ]:
b = np.array(a)
b

In [ ]:
b[np.isnan(b)]

In [ ]:
#Using ~ (NOT) bit-wise operator
b[~np.isnan(b)]

# Data Types 

#### Float point arithmatics 

###### pandas 

In [ ]:
a = pd.DataFrame({"a":[1, 2, 3]})
a

In [ ]:
a.dtypes

In [ ]:
a = a["a"].astype("float64")
a

###### numpy 

In [39]:
a = np.float16(1.010300303030303030303030303030)
print(a)
print(type(a))
print(a.dtype)

1.011
<class 'numpy.float16'>
float16


In [22]:
#See how you can never retrieve the original float values
a = a.astype("float64")
a

1.0107421875

###### python to numpy dtypes 

In [35]:
b = 1.010300303030303030303030303030
print(type(b))
print(b)

<class 'float'>
1.010300303030303


In [36]:
c = np.float128(b)
print(c)

1.0103003030303030485


###### Rounding Error Case 1 

In [ ]:
#Compute and append momentum difference between measured p and calculated p using theta and phi
def comp_p_diff_abs(el_p_abs, theta, phi):
    
    #Difference of measured momentum from drift chamber to the calculated momentum using measured momentum from dc, theta, phi
    p_diff_abs = np.sqrt(pow(el_p_abs, 2)*(pow(np.cos(np.deg2rad(phi)), 2) * pow(np.sin(np.deg2rad(theta)), 2) + 
                                           pow(np.sin(np.deg2rad(phi)), 2) * pow(np.sin(np.deg2rad(theta)), 2) +
                                           pow(np.cos(np.deg2rad(theta)), 2))) - el_p_abs
    return p_diff_abs

#Vectorize
#    -NEED THE OUTPUT TYPE TO BE np.float16 to remove float-point rounding error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
vect_comp_p_diff_abs  = np.vectorize(comp_p_diff_abs, otypes=[np.float16])

#Compute
p_diff_abs            = vect_comp_p_diff_abs(df_GMSH["el_p_abs"].values, df_GMSH["theta"].values, df_GMSH["phi"].values)

#Append
df_GMSH["p_diff_abs"] = pd.Series(p_diff_abs, index=df_GMSH.index)v

In [ ]:
#Changing the datatype of a column to avoid rouding error
df_GMSH["p_diff_abs"] = df_GMSH["p_diff_abs"].astype("float16")

In [ ]:
df_GMSH["p_diff_abs"].dtype

# Optimization 

###### Looping over rows using "iloc" 

In [13]:
#Haversine fn 
#    -takes latitude and longitude of two points, adjust for Earth's curvature, then calculate the straight-line distance

def haversine(lat1, lon1, lat2, lon2):
    MILES = 3959
    #Convert degrees to radians - "map" function lets np.deg2rad fn to each elements in the following list
    lat1, lon1, lat2, lon2 = map(np.deg2rad, [lat1, lon1, lat2, lon2])
    
    #distance in rad
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    #Compute
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    total_miles = MILES * c
    
    return total_miles

In [14]:
#Data 
#    -Coordinates of all hotels in NY
df = pd.read_csv("./python_optimize/new_york_hotels.csv", encoding="cp1252")
df.head()

ean_hotel_id                                     name  \
0        269955       Hilton Garden Inn Albany/SUNY Area   
1        113431     Courtyard by Marriott Albany Thruway   
2        108151                    Radisson Hotel Albany   
3        254756  Hilton Garden Inn Albany Medical Center   
4        198232  CrestHill Suites SUNY University Albany   

                 address1    city state_province postal_code  latitude  \
0     1389 Washington Ave  Albany             NY       12206  42.68751   
1  1455 Washington Avenue  Albany             NY       12206  42.68971   
2             205 Wolf Rd  Albany             NY       12205  42.72410   
3     62 New Scotland Ave  Albany             NY       12208  42.65157   
4  1415 Washington Avenue  Albany             NY       12206  42.68873   

   longitude  star_rating  high_rate  low_rate  
0  -73.81643          3.0   154.0272  124.0216  
1  -73.82021          3.0   179.0100  134.0000  
2  -73.79822          3.0   134.1700   84.1600  
3  -73.77638          3.0   308.2807  228.4597  
4  -73.81854          3.0   169.3900   89.3900

In [15]:
def haversine_looping(df):
    distance_list = []
    
    for i in range(0, len(df)):
        d = haversine(40.671, -73.985, df.iloc[i]["latitude"], df.iloc[i]["longitude"])
        distance_list.append(d)
    
    return distance_list

In [16]:
%%time

df['distance'] = haversine_looping(df)

CPU times: user 916 ms, sys: 0 ns, total: 916 ms
Wall time: 916 ms


###### Iterrows 

In [17]:
def haversine_iterrows(df):
    distance_list = []

    for index, row in df.iterrows():
        d = haversine(40.671, -73.985, row["latitude"], row["longitude"])
    
        distance_list.append(d)
        
    return distance_list

In [ ]:
%%time

df["distance"] = haversine_iterrows(df)

###### apply() + lambda 

In [19]:
def haversine_apply_lambda(df):
    series = df.apply(lambda row: haversine(40.671, -73.985, row["latitude"], row["longitude"]), axis=1)
    return series

In [ ]:
%%time

df["distance"] = haversine_apply_lambda(df)

###### Vectorization - pandas Series 

In [21]:
def haversine_vec_pd(df):
    series = haversine(40.671, -73.985, df["latitude"], df["longitude"])
    return series

In [ ]:
%%time

df["distance"] = haversine_vec_pd(df)

###### Vectorization - numpy

In [23]:
#Haversine fn 
#    -takes latitude and longitude of two points, adjust for Earth's curvature, then calculate the straight-line distance

def haversine(lat1, lon1, lat2, lon2):
    MILES = 3959
    #Convert degrees to radians - "map" function lets np.deg2rad fn to each elements in the following list
    lat1, lon1, lat2, lon2 = map(np.deg2rad, [lat1, lon1, lat2, lon2])
    
    #distance in rad
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    #Compute
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    total_miles = MILES * c
    
    return total_miles

In [24]:
series = haversine(40.671, -73.985, df["latitude"].values, df["longitude"].values)

In [25]:
def haversine_vec_np(df):
    series = haversine(40.671, -73.985, df["latitude"].values, df["longitude"].values)
    return series

In [ ]:
%%time

df["distance"] = haversine_vec_np(df)

###### Vectorization w/ IF statements - numpy - np.vectorize() - THIS IS IT!!!

In [6]:
# Number of test points
N_point  = 1000

In [7]:
# List of stored elements, generated from a Normal distribution
lst_x      = np.random.randn(N_point)
lst_y      = np.random.randn(N_point)
lst_result = []

In [8]:
#Define a custom function with if-else - TO BE USED FOR VECTORIZATION methods
def myfunc(x, y):
    if (x > 0.5*y and y < 0.3):
        return (math.sin(x-y))
    elif (x < 0.5*y):
        return 0
    elif (x > 0.2*y):
        return (2*math.sin(x + 2*y))
    else:
        return (math.sin(y + x))

In [ ]:
# Numpy.vectorize method
t1 = time.time()
#--------------------np.vectorize()-----------------------------
#--------------------np.vectorize()-----------------------------
#--------------------np.vectorize()-----------------------------
vectfunc = np.vectorize(myfunc,otypes=[np.float],cache=False)
#--------------------np.vectorize()-----------------------------
#--------------------np.vectorize()-----------------------------
#--------------------np.vectorize()-----------------------------
result   = list(vectfunc(lst_x,lst_y))

t2 = time.time()
print("computation time = ", t2 - t1)

In [ ]:
x = np.array(result)
print(x)
print(x.shape)

###### Other ways - iloc, list compreh, map() 

In [ ]:
# First, plain vanilla for-loop
t1 = time.time()
for i in range(len(lst_x)):
    x = lst_x[i]
    y = lst_y[i]
    if (x > 0.5*y and y < 0.3):
        lst_result.append(math.sin(x-y))
    elif (x < 0.5*y):
        lst_result.append(0)
    elif (x > 0.2*y):
        lst_result.append(2*math.sin(x+2*y))
    else:
        lst_result.append(math.sin(y+x))
t2=time.time()

print("computation time = ", t2 - t1)

In [ ]:
# List comprehension
t1 = time.time()

lst_result = [myfunc(x,y) for x,y in zip(lst_x,lst_y)]

t2 = time.time()
print("computation time = ", t2 - t1)

In [ ]:
# Map() function
t1 = time.time()

list(map(myfunc,lst_x,lst_y))

t2 = time.time()
print("computation time = ", t2 - t1)

In [ ]:
#Map() + lambda
t1 = time.time()

list(map(lambda x : x*2, [1, 2, 3, 4]))

t2 = time.time()
print("computation time = ", t2 - t1)